import './globals.css'
import { Inter } from 'next/font/google'
import { clerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <clerkProvider>
        <html lang="en">
        <body className={inter.className}>
          <main className="container">
            <div className="flex items-start justify-content min-h-screen">
              <div className="mt-20">{children}</div>
            </div>
          </main>
        </body>
        </html>
    </clerkProvider>
  )
}
